name: Publish Docker image to GHCR

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  build-and-push:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract version from tag
        id: meta
        run: |
          RAW="${GITHUB_REF#refs/tags/}"; echo "VERSION=${RAW#v}" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/ph-ee-ai-bot:${{ steps.meta.outputs.VERSION }}
            ghcr.io/${{ github.repository }}/ph-ee-ai-bot:latest
          platforms: linux/amd64
